version: '3.7'

services: 
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports: 
      - '3000:3000'
    # environment: 
    #   - MYSQL_USERNAME=root
    #   - MYSQL_ROOT_PASSWORD=1234
    #   - MYSQL_DATABASE=gpsv3_system
    volumes: 
      - ./docker/data:/var/lib/grafana
      - ./docker/logs:/var/log/grafana
# - data /var/lib/grafana
# - logs /var/log/grafana
