global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    dc: dc1

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'prometheus:9100'
        - 'consul:9100'

  - job_name: 'file_sd'
    file_sd_configs:
      - files:
        - custom_file_sd.json
