global:
  scrape_interval:     30s
  scrape_timeout:      5s
  evaluation_interval: 1m
  external_labels:
    dc: dc1
    prom: prom1

rule_files:
  - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['prometheus:9100']

